env:
  es6: true
  node: true
extends:
  - 'eslint:recommended'
parserOptions:
  ecmaVersion: 2017
  sourceType: module
globals:
  document: readonly
rules:
  max-len:
    - error
    - code: 79
    - comments: 69
  no-trailing-spaces:
    - error
  eol-last:
    - error
  no-multiple-empty-lines:
    - error
    - max: 1
  indent:
    - error
    - 2
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console: 0
  no-unused-vars:
    - warn
