language: node_js
node_js:
    - node
    - '7'
    - '6'
python:
    - '3.5'
sudo: required
dist: trusty
services:
    - docker
before_install:
    - sudo apt-get -y install python3-pip python-dev
    - sudo pip3 install -U setuptools
    - sudo pip3 install -U virtualenvwrapper
    - sudo apt-get install xvfb
install:
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - docker pull auvsisuas/interop-server
    - docker images
    - npm install
    - npm install -g mocha
script:
    - for i in {1..5}; do npm test && break || (sleep 10; docker pull auvsisuas/interop-server); done
notifications:
    email: false
