language: node_js
node_js:
    - '8'
    - '7'
    - '6'
sudo: required
dist: trusty
services:
    - docker
branches:
    only:
        - master
        - development
        - /^release-.*$/
        - /^hotfix-.*$/
before_install:
    - sudo apt-get -y install python3-pip python-dev
    - sudo pip3 install -U setuptools
    - sudo pip3 install -U virtualenvwrapper
    - sudo apt-get install xvfb
install:
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - docker pull auvsisuas/interop-server
    - docker images
    - npm install
    - npm install -g mocha
script:
    - ./scripts/run-tests-repeat
notifications:
    email: false
